In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Iris (2).csv")

In [ ]:
df.dtypes


Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
df.drop(columns=['Id'], inplace=True)

In [ ]:
Q1 = df.iloc[:, :-1].quantile(0.25)  # First quartile (Q1)
Q3 = df.iloc[:, :-1].quantile(0.75)  # Third quartile (Q3)
IQR = Q3 - Q1  # Interquartile Range

# Define valid range (1.5 * IQR rule)
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter out rows with outliers
df_filtered = df[~((df.iloc[:, :-1] < lower_bound) | (df.iloc[:, :-1] > upper_bound)).any(axis=1)]

In [ ]:
X = df_filtered.iloc[:, :-1].values
y = df_filtered.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
# Train-test split (80-20 for better accuracy)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(X_test)

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Compute Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

# Compute TP, FP, FN, TN for Multi-Class
TP = np.diag(cm)  # True Positives (Diagonal elements)
FP = cm.sum(axis=0) - TP  # False Positives (Column sum - TP)
FN = cm.sum(axis=1) - TP  # False Negatives (Row sum - TP)
TN = cm.sum() - (TP + FP + FN)  # True Negatives (Total sum - others)

# Compute Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='macro')  # 'macro' for multi-class
recall = recall_score(y_test, y_pred, average='macro')

# Display Results
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.4f}")
print(f"Error Rate: {error_rate:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

# Print TP, FP, FN, TN for each class
for i, class_name in enumerate(np.unique(y_test)):  # Assuming label encoding
    print(f"\nClass: {class_name}")
    print(f"TP: {TP[i]}, FP: {FP[i]}, FN: {FN[i]}, TN: {TN[i]}")


Confusion Matrix:
 [[12  0  0]
 [ 0  7  1]
 [ 0  1  9]]
Accuracy: 0.9333
Error Rate: 0.0667
Precision: 0.9250
Recall: 0.9250

Class: 0
TP: 12, FP: 0, FN: 0, TN: 18

Class: 1
TP: 7, FP: 1, FN: 1, TN: 21

Class: 2
TP: 9, FP: 1, FN: 1, TN: 19
